name: Build and push server Helm Chart to ECR

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'helm/**'

env:
  ECR_REGISTRY: 917563509651.dkr.ecr.eu-west-1.amazonaws.com
  AWS_REGION: "eu-west-1"

permissions:
  id-token: write
  contents: read

jobs:
  helm-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - uses: alexellis/arkade-get@master
      with:
        helm: latest

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::917563509651:role/github-oidc-medusa-starter
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Package and push helm chart to Amazon ECR
      run: |
        helm package ./helm
        NAME=$(awk '/^name:/ {print $2; exit}' ./helm/Chart.yaml)
        VERSION=$(cat ./helm/Chart.yaml | grep version: | awk '{print $2}')
        helm push $NAME-$VERSION.tgz oci://$ECR_REGISTRY